### ISSUE TITLE
expressions in trait impls

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/project-const-generics#12]
Currently we dont permit expressions in trait impls without also using params directly i.e. [this code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=14997c43610a59e429bffbb6e6b87799) fails to compile:
```rust
#![feature(const_generics, const_evaluatable_checked)]
#[allow(incomplete_features)]

trait Foo<const N: usize> {}
struct Bar;

impl<const N: usize> Foo<{N + 1}> for Bar {}
```
with this error message:
```
error[E0207]: the const parameter `N` is not constrained by the impl trait, self type, or predicates
 --> src/lib.rs:7:12
  |
7 | impl<const N: usize> Foo<{N + 1}> for Bar {}
  |            ^ unconstrained const parameter
  |
  = note: expressions using a const parameter must map each value to a distinct output value
  = note: proving the result of expressions other than the parameter are unique is not supported

error: aborting due to previous error; 2 warnings emitted
```

this also means the [following code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=2a936fd88cb8fd977e9376b58bfb7b58) doesn't compile either:
```rust
#![feature(const_generics, const_evaluatable_checked)]
#[allow(incomplete_features)]

trait Foo<const N: Option<bool>> {}
struct Bar;

impl<const N: bool> Foo<{ Some(N) }> for Bar {}
```
but it seems like we should allow ^^^^^^ this

**Comment by oli-obk** [comment]
Yea, considering that the "equivalent"

```rust
trait Foo<N> {}
struct Bar;

struct Meh<T>(T);

impl<N> Foo<Meh<N>> for Bar {}
```

compiles, we should allow this. Not sure if that is a new source of cycle errors though

**Comment by lcnr** [comment]
superseded by #23
