### ISSUE TITLE
review policy

### ISSUE THREAD

**Issue by lcnr** [rust-lang/project-const-generics#4]
Hi folks,

do we want some kind of explicit review policy for this repo?
I personally would prefer us to just directly merge typo fixes and the likes
while still requiring someone else to approve/merge anything more complex.

If this seems good to you all the other question is how we want to notify reviewers?
Do we just expect enough people to watch this repo, should we explicitly ping the whole project group
or more selectively try and ping individual people?

I think watching the repo is probably easiest while also allowing some of us to stop
watching the repo in case they do not want to get notified for everything.

cc @rust-lang/project-const-generics

**Comment by varkor** [comment]
I agree that for now merging small fixes and watching the repository should work for now.

**Comment by oli-obk** [comment]
I'm watching the repo. Just like the const-eval repo, I don't expect excessive traffic here and thus will just look at everything that happens

**Comment by lcnr** [comment]
seems good ^^
